apiVersion: v1
kind: PersistentVolume
metadata:
  name: termination-log-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/termination-logs # This is a directory on your host machine where the logs will be stored
    type: DirectoryOrCreate
