apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: termination-log-pvc
  namespace: webserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
