apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: webserver
spec:
  selector:
    app: webserver-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort